### PR TITLE
ES6 compatibility

### PR DESCRIPTION
**Pull request by pmourlanne**
Closes https://github.com/pmourlanne/fiqs/issues/2

TODO:

- [x] Stop using our `Model` class and start using what's in elasticsearch-dsl? -> Probably is too late for that X)
- [x] Look into `Nested` -> `InnerDoc` change https://elasticsearch-dsl.readthedocs.io/en/latest/Changelog.html#id11
- [x] Re-generate search outputs with `pytest -m docker`
- [x] Fix tests
- [x] Documentation
- [x] Release

@jgb FYI :O

### CODE REVIEW

**Comment by pmourlanne** [comment]
@jgb I'll let you test this branch with your code. I'll make a release once everything works

**Comment by jgb** [comment]
@pmourlanne I owe you, big time! Going to test straight away and let you know :)

**Comment by jgb** [comment]
@pmourlanne first report looks good! Previously we had a total of 869 tests failing when I run everything on ES6, with the es6 branch of fiqs I'm down to 78 failures!
Many of them follow the same style:

`
self = <vidicenter.common.fiqs.FQueryExt object at 0x7fae9a933978>, result = <Response: {'clips': {'doc_count': 3, 'clip_id': {'doc_count_error_uppe...}>, flat = True, fill_missing_buckets = True, add_others_line = False                   
                                                                                                                                                                                                                                               
    def prepare_result(self, result, flat=True, fill_missing_buckets=True, add_others_line=False):                                                                                                                                             
        if flat:                                                                                                                                                                                                                               
            lines = self._flatten_result(                                                                                                                                                                                                      
                result,                                                                                                                                                                                                                        
                add_others_line=add_others_line,                                                                                                                                                                                               
                remove_nested_aggregations=self._contains_nested_expressions(),                                                                                                                                                                
            )                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                               
            if fill_missing_buckets:                                                                                                                                                                                                           
>               lines = self._add_missing_lines(result, lines)                                                                                                                                                                                 
E               TypeError: _add_missing_lines() takes 2 positional arguments but 3 were given                                                                                                                                                  
                                                                                                                                                                                                                                               
common/fiqs.py:122: TypeError                                                                                     
`

I guess some of our fiqs related code has to updated.

**Comment by jgb** [comment]
@pmourlanne ah I can see where it's coming from, apparently we are using (abusing? :santa: ) an internal fiqs api: https://github.com/pmourlanne/fiqs/commit/a8e7c3f7edf118a3daa380286a55ff0c063dd06b

**Comment by jgb** [comment]
@pmourlanne after updating our fiqs code to use the new method signature for _add_missing_lines we are down to ZERO test failures, amazing! :1st_place_medal: :+1: :fireworks:

**Comment by pmourlanne** [comment]
I'll try to make a release soon :+1:

**Comment by jgb** [comment]
> I'll try to make a release soon

Beep beep! :rose:

**Comment by pmourlanne** [comment]
https://pypi.org/project/fiqs/0.4.0/

**Pull request merged**
